CREATE TABLE ResetAttempts (
    ID CHAR(26) NOT NULL,
    UserID CHAR(26) NOT NULL,
    Token CHAR(6) NOT NULL,
    ValidUntil DATETIME NOT NULL,
    Succeed BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID),
    FOREIGN KEY FKResetAttemptsUsers (UserID)
    REFERENCES Users (ID)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;
