CREATE TABLE Bookmarks (
    ID CHAR(26) NOT NULL,
    UserID CHAR(26) NOT NULL,
    PostID CHAR(26) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID),
    FOREIGN KEY FKBookmarksUsers (UserID) REFERENCES Users (ID) 
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY FKBookmarksPosts (PostID) REFERENCES Posts (ID) 
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;