CREATE TABLE Comments (
    ID CHAR(26) NOT NULL,
    PostID CHAR(26) NOT NULL,
    UserID CHAR(26) NOT NULL,
    Value TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID),
    FOREIGN KEY FKCommentsPosts (PostID) REFERENCES Posts (ID) 
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY FKCommentsUsers (UserID) REFERENCES Users (ID) 
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;