CREATE TABLE Users (
    ID CHAR(26) NOT NULL PRIMARY KEY,
    FullName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    HashedPassword CHAR(60) NOT NULL,
    ProfilePicture VARCHAR(255),
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL
);
