name: 🪄 Lint Go Code

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  golangci-lint:
    name: Lint ✨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          # NOTE: Keep this in sync with the version from go.mod
          go-version: "1.22.x"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # NOTE: Keep this in sync with the version from .golangci.yml
          version: v1.56.2
