name: Deploy OpenAPI Specification with Swagger to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - "master"
    # paths:
    #   - "openapi.yaml"

jobs:
  deploy:
    name: 💫 Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Get latest code
        uses: actions/checkout@v4
      - name: 🐳 Run Container
        uses: addnab/docker-run-action@v3
        with:
          image: swaggerapi/swagger-ui:v5.10.5
          options: --name swagger_doc --env SWAGGER_JSON=/openapi.yaml
      - name: 📂 Copy Generated Swagger UI
        run: |-
          echo "Copying generated doc files to Runner"
          docker cp swagger_doc:/usr/share/nginx/html ${{ github.workspace }}/doc
          cp ${{ github.workspace }}/openapi.yaml ${{ github.workspace }}/doc
          sed -i 's/(https://petstore.swagger.io/v2/swagger.json){1}/.openapi.yaml//g' ${{ github.workspace }}/doc/swagger-initializer.js
          cat ${{ github.workspace }}/doc/swagger-initializer.js
      # - name: 🚀 Deploy to Vercel
      #   working-directory: ${{ github.workspace }}/doc
      #   run: |-
      #     npm install --global vercel@latest
      #     vercel --token=${{ secrets.VERCEL_TOKEN }} --prod
