name: Deploy SwaggerUI OAS 3.1 to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    paths:
      - "openapi.yaml"

jobs:
  build:
    name: 💫 Generate SwaggerUI & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Get latest code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |-
            openapi.yaml
          sparse-checkout-cone-mode: false
      - name: 🐳 Run Container
        uses: addnab/docker-run-action@v3
        with:
          image: swaggerapi/swagger-ui:v5.10.5
          options: --name swagger_doc
      - name: 📂 Copy Generated Swagger UI
        shell: bash
        run: |-
          echo "Copying generated doc files to Runner"
          docker cp swagger_doc:/usr/share/nginx/html ${{ github.workspace }}/doc
          cp ${{ github.workspace }}/openapi.yaml ${{ github.workspace }}/doc
          sed -i 's/https:\/\/petstore.swagger.io\/v2\/swagger.json/.\/openapi.yaml/g' ${{ github.workspace }}/doc/swagger-initializer.js
      - name: 🚀 Deploy to Vercel
        working-directory: ${{ github.workspace }}/doc
        run: |-
          npm install --global vercel@latest
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod
